alias gba='git branch -a'
alias gcm='git checkout master'
alias glpp='git log --pretty=oneline'
alias gs='git status'
alias gd='git diff'
alias gci='git commit --interactive'
alias ga='gitk --all'
alias gmt='git mergetool'

alias upb='git checkout production && git merge origin/master && git push && git checkout master'